FROM node:18-alpine AS builder
WORKDIR /tmp/builder

COPY . .

RUN npm i
RUN npm run build 

# ---- #

FROM node:18-alpine
WORKDIR /usr/src/app

ARG MONGODB_URI
ARG MONGODB_PORT

COPY --from=builder ./tmp/builder/dist .
COPY package*.json .

RUN npm i --omit=dev

ENTRYPOINT [ "node", "index.js" ]
