FROM node:16-alpine AS builder
WORKDIR /tmp/builder

COPY . .

RUN npm i -g typescript
RUN tsc 

# ---- #

FROM node:16-alpine
WORKDIR /usr/src/app

ARG MONGODB_URI
ARG MONGODB_PORT

COPY /tmp/builder/dist/ .
COPY package*.json .

RUN npm ci --only=production

ENTRYPOINT [ "node", "index.js" ]