FROM node:20-alpine AS builder
WORKDIR /tmp/builder

RUN npm i -g typescript
RUN tsc 

# ---- #

FROM node:20-alpine
WORKDIR /usr/src/app

ARG MONGODB_URI
ARG MONGODB_PORT

COPY ./dist/ .
COPY package*.json .

RUN npm i --omit=dev

ENTRYPOINT [ "node", "index.js" ]
