apiVersion: apps/v1
kind: Deployment
metadata:
  name: w830-logger-deployment
  labels:
    app: w830-logger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: w830-logger
  template:
    metadata:
      labels:
        app: w830-logger
    spec:
      containers:
        - name: w830-logger
          image: registry.sinding.net/w830-logger:1.1.4
          ports:
            - name: api
              containerPort: 9000

---
apiVersion: v1
kind: Service
metadata:
  name: w830-logger-svc
spec:
  selector:
    app: w830-logger
  ports:
    - protocol: TCP
      name: api-port
      port: 9000
      targetPort: api
